### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by catmeme** [grimwm/py-jstree#3]
Doesn't look like this module is actively maintained but I thought I'd give it a go anyway. Unfortunately, it seems like the example I tried is broken.

Test:

```
import jstree
paths = [jstree.Path("editor/2012-07/31/.classpath", 1), jstree.Path("editor/2012-07/31/.project", 2)]
print(jstree.JSTree(paths).pretty())
```

Result:

```
Traceback (most recent call last):
  File "./bin/test.py", line 60, in <module>
    print(jstree.JSTree(paths).pretty())
  File "/home/catmeme/dev/test/venv/lib/python3.4/site-packages/jstree.py", line 102, in __init__
    if len(filter(lambda p: not isinstance(p, Path), paths)):
TypeError: object of type 'filter' has no len()
```

**Comment by grimwm** [comment]
What version of Python are you running?  That code executed cleanly in Python 2.7.9.

**Comment by grimwm** [comment]
I can see that this is causing problems in Python 3.  I will work on updating the tests, but first I have to bring py-dictobj up to speed.

**Comment by grimwm** [comment]
Hi again.  Please update your version of jstree with "pip install --upgrade jstree" and try again.  I've upgraded it and the supporting py-dictobj to work with Python 3.

**Comment by catmeme** [comment]
@grimwm Yes I /am using Python 3. I have verified this is now resolved. Thank you.
